# Proyecto Python
# Copia este archivo a la raíz de tu proyecto con el nombre: sonar-project.properties
# ⚠️ NO pongas el token aquí: se pasa con -Dsonar.token=$SONAR_TOKEN

sonar.projectKey=CAMBIAR-por-tu-project-key
sonar.projectVersion=fase1
sonar.host.url=http://localhost:9000

sonar.sources=.
sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/tests/**,**/test_*.py,**/reports-dc/**,htmlcov/**,coverage.xml,semgrep.sarif
# Ajusta a tu versión de Python
sonar.python.version=3.12

# Paso 6 · Semgrep
# sonar.sarifReportPaths=semgrep.sarif

# Paso 7 · Dependency-Check (opcional). En Python el comando lleva --enableExperimental
# sonar.dependencyCheck.jsonReportPath=reports-dc/dependency-check-report.json
# sonar.dependencyCheck.htmlReportPath=reports-dc/dependency-check-report.html

# Paso 10 · Cobertura (Fase 2), generada con: pytest --cov --cov-report=xml
# sonar.python.coverage.reportPaths=coverage.xml
